### PR TITLE
Fix issue that breaks mini cart loading after order with coupon code …

### PR DESCRIPTION
**Pull request by ivangraybox**
…is placed

### CODE REVIEW

**Comment by saschabratton** [comment]
Thanks for the PR.

I'm not totally clear what the intention was originally with attempting to generate a coupon code if a coupon code was used. It seems like maybe the idea was to not generate a code on conversion when cart code generation is turned on -- there's a guard statement on if a promo code is set -- but this seems like an odd way to accomplish it and placing the assignment within the conditional seems like a bad practice.

I think it is technically against code standards, as it is really two separate statements in one line. I will adjust.

Can you confirm that the error you are receiving is due to the lack of a $rule_id parameter on the call to `generateCouponCode` method?

If so, I think we can better resolve this by guarding for it within the `generateCouponCode` method, and I'd be happy to implement it like this, if it will fix your issue.

**Comment by ivangraybox** [comment]
You're right, the core issue is missing `$rule_id`. But I'm thinking we don't even need it. This code is working after you place an order so if there was a coupon code applied it supposed to be sent to Rejoiner along with order ID for tracking reason I believe. And because `getCouponCode()` returns an actual coupon code applied there is no sense to load it using `generateCouponCode()`. So (if coupon code needs to be sent to Rejoiner) the easiest way is to use `$promo`.

**Comment by saschabratton** [comment]
@ivangraybox Thanks! It's helpful to confirm the issue you're seeing to ensure we are solving your problem with any fix.

I think we may want to just move away from using the `promo` parameter for auto-generation coupon codes. I believe this was done due to lack of support for custom parameters in the past, which is no longer an issue. In that case, simply setting the `promo` to be the coupon code use on the purchase, as your PR proposes, may be the better solution here.

**Comment by ivangraybox** [comment]
@saschabratton, thank you for your quick replies.

**Comment by saschabratton** [comment]
Since this was not working and this fix solves your immediate issue, I've gone ahead and merged this in as v2.5.1 which you can use right away. We have some pending updates coming down the pipe, which will get this merged, but we are also going to add some more implementation to support cart code auto-generation on the conversion events.

Thanks again :)

**Comment by ivangraybox** [comment]
@saschabratton, I'm not seeing the new version on the releases page ( https://github.com/rejoiner/magento2-plugin/releases ). Can you please check and publish it so we can access?

**Comment by saschabratton** [comment]
@ivangraybox I've added the release here: https://github.com/rejoiner/magento2-plugin/releases/tag/2.5.1

**Comment by ivangraybox** [comment]
Thank you!

**Pull request merged**
